#!/usr/bin/env python3
"""
Repository smoke tests.

These do not train anything. They check the things that silently rot when code
is moved or results are regenerated by hand:

  * every module still imports (catches a moved or deleted dependency)
  * every result CSV parses, has no blank metric cells, and covers the folds
    it claims to (catches a half-written row appended by hand)
  * the manifests still satisfy the genome-level no-leakage invariant
  * paths referenced by the README and by script defaults actually exist

Run from the repository root:

    python3 -m pytest tests/ -q
    python3 tests/test_smoke.py        # also works without pytest

The import test needs torch, so run it inside the container:

    apptainer exec patbinn.sif python3 -m pytest tests/ -q
"""

import collections
import csv
import glob
import importlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Modules live in src/ and import each other directly, exactly as they do when
# a driver is run as `python3 src/<script>.py` (Python puts the script's own
# directory on sys.path).
sys.path.insert(0, os.path.join(ROOT, "src"))

MODULES = [
    "BNN_model", "kmer_encoding", "moe_model", "moe_dataset", "training_utils",
    "train_moe", "train_flat", "train_final_model",
    "evaluate_moe", "evaluate_flat",
    "run_cv", "aggregate_cv_results", "run_encoding_experiment",
    "sweep_architecture", "sweep_cross_combos", "sweep_error_rates",
    "sweep_experts", "sweep_read_counts", "sweep_router",
    "compare_kraken2", "plot_results",
]

# Result files and the metric columns that must be fully populated.
RESULT_SPECS = {
    "results/cv_results.csv": ["sample_leaf_acc_pipeline", "per_read_router_acc"],
    "results/cv_results_float32.csv": ["sample_leaf_acc_pipeline"],
    "results/cv_results_flat.csv": ["sample_leaf_acc", "per_read_leaf_acc"],
    "results/router_sweep.csv": ["router_params", "per_read_router_acc"],
    "results/expert_sweep.csv": ["expert_params_total", "per_read_expert_acc_oracle"],
    "results/encoding_variants.csv": ["sample_leaf_acc_pipeline"],
    "results/read_count_sweep.csv": ["sample_family_acc", "sample_leaf_acc_pipeline",
                                      "sample_variant_acc_oracle"],
    "results/error_rate_sweep.csv": ["per_read_leaf_acc", "sample_leaf_acc_pipeline"],
    "results/patbinn_fold1_error_sweep.csv": ["per_read_leaf_acc"],
    "results/canonical_fold1_error_sweep.csv": ["sample_leaf_acc_pipeline"],
    "results/kraken2_error_sweep.csv": ["per_read_variant_acc", "pct_unclassified"],
    "results/kraken2_sample_acc_normalized.csv": ["sample_variant_acc_lenient",
                                                   "sample_variant_acc_strict"],
}


def _rows(path):
    with open(os.path.join(ROOT, path), newline="") as f:
        return list(csv.DictReader(f))


def test_all_modules_import():
    """Every module imports. Catches a dependency moved or deleted."""
    failures = []
    for m in MODULES:
        try:
            importlib.import_module(m)
        except Exception as e:  # noqa: BLE001 - report, don't mask
            failures.append(f"{m}: {type(e).__name__}: {e}")
    assert not failures, "modules failed to import:\n  " + "\n  ".join(failures)


def test_result_files_exist_and_parse():
    """Every result file referenced by the docs exists and is non-empty."""
    missing = [p for p in RESULT_SPECS if not os.path.exists(os.path.join(ROOT, p))]
    assert not missing, f"missing result files: {missing}"
    empty = [p for p in RESULT_SPECS if not _rows(p)]
    assert not empty, f"result files with no data rows: {empty}"


def test_no_blank_metric_cells():
    """No result row has a blank metric.

    A partially written row (e.g. appended by hand with only one column filled)
    parses fine as CSV but crashes any consumer that calls float() on it.
    """
    problems = []
    for path, cols in RESULT_SPECS.items():
        for i, row in enumerate(_rows(path), start=2):
            for c in cols:
                if c not in row:
                    problems.append(f"{path}: missing column {c!r}")
                elif not (row[c] or "").strip():
                    problems.append(f"{path} line {i}: blank {c!r}")
    assert not problems, "blank or missing metric cells:\n  " + "\n  ".join(problems)


def test_metrics_are_percentages():
    """Accuracy columns are percentages in [0, 100], not fractions."""
    bad = []
    for path, cols in RESULT_SPECS.items():
        for i, row in enumerate(_rows(path), start=2):
            for c in cols:
                if "acc" not in c and "pct" not in c:
                    continue
                v = float(row[c])
                if not 0.0 <= v <= 100.0:
                    bad.append(f"{path} line {i}: {c}={v}")
    assert not bad, "accuracy values outside [0, 100]:\n  " + "\n  ".join(bad)


def test_cv_covers_five_folds():
    """Each CV condition has exactly five folds, 0-4."""
    for path in ["results/cv_results.csv", "results/cv_results_float32.csv",
                 "results/cv_results_flat.csv"]:
        folds = sorted(int(r["fold"]) for r in _rows(path))
        assert folds == [0, 1, 2, 3, 4], f"{path}: expected folds 0-4, got {folds}"

    for sub in ["cv_hierarchical_binary", "cv_hierarchical_float32", "cv_flat_binary"]:
        found = glob.glob(os.path.join(ROOT, "results", sub, "fold*_result.json"))
        assert len(found) == 5, f"results/{sub}: expected 5 fold JSONs, found {len(found)}"


def test_genome_manifest_no_leakage():
    """The core invariant: one isolate belongs to exactly one fold.

    If an isolate straddled folds, its reads could appear in both train and
    test, and "held-out genome" would silently stop being true.
    """
    rows = _rows("data/manifests/genome_manifest_multi.csv")
    folds = collections.defaultdict(set)
    for r in rows:
        folds[(r["family"], r["variant"], r["isolate_idx"])].add(r["fold"])
    straddling = {k: v for k, v in folds.items() if len(v) > 1}
    assert not straddling, f"isolates assigned to multiple folds: {list(straddling)[:5]}"


def test_sample_manifest_no_leakage():
    """Same invariant one level down: every replicate of an isolate shares its fold."""
    rows = _rows("data/manifests/cv_sample_manifest.csv")
    folds = collections.defaultdict(set)
    for r in rows:
        folds[(r["family"], r["variant"], r["isolate_idx"])].add(r["fold"])
    straddling = {k: v for k, v in folds.items() if len(v) > 1}
    assert not straddling, f"isolates whose replicates span folds: {list(straddling)[:5]}"


def test_dataset_shape_matches_docs():
    """The dataset is the size the documentation claims."""
    genomes = _rows("data/manifests/genome_manifest_multi.csv")
    classes = {(r["family"], r["variant"]) for r in genomes}
    families = {r["family"] for r in genomes}
    assert len(genomes) == 543, f"docs say 543 genomes, manifest has {len(genomes)}"
    assert len(classes) == 58, f"docs say 58 classes, manifest has {len(classes)}"
    assert len(families) == 8, f"docs say 8 families, manifest has {len(families)}"

    per_class = collections.Counter((r["family"], r["variant"]) for r in genomes)
    assert min(per_class.values()) >= 3, (
        "docs claim every class has at least 3 independent isolates; "
        f"minimum is {min(per_class.values())}"
    )


def test_paths_referenced_by_docs_exist():
    """Files the README Quickstart and script defaults point at are present."""
    required = [
        "README.md", "LICENSE", "requirements.txt", "patbinn.def", ".gitignore",
        "src/run_cv.py", "src/train_moe.py", "src/evaluate_moe.py",
        "src/plot_results.py", "src/aggregate_cv_results.py",
        "data/download_genomes.py", "data/simulate_reads.py",
        "data/manifests/generalization_manifest.csv",
        "data/manifests/cv_sample_manifest.csv",
        "data/manifests/genome_manifest_multi.csv",
        "docs/ARCHITECTURE.md", "docs/PIPELINE.md", "docs/EXPERIMENTS.md",
        "docs/RESULTS.md", "docs/GENOME_INVENTORY.txt",
        "data/README.md", "results/README.md", "scripts/README.md",
        "scripts/make_genome_inventory.py",
    ]
    missing = [p for p in required if not os.path.exists(os.path.join(ROOT, p))]
    assert not missing, f"referenced but missing: {missing}"


def _tracked_text_files():
    """Files git actually publishes. Ignored leftovers on disk don't count."""
    import subprocess
    try:
        out = subprocess.run(["git", "-C", ROOT, "ls-files"],
                             capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    exts = (".py", ".md", ".def", ".sh", ".txt", ".cff", ".yml", ".yaml")
    return [p for p in out.stdout.split("\n") if p.endswith(exts)]


def test_documented_invocation_paths_resolve():
    """Every `python3 <path>.py` in the docs and job scripts points at a real file.

    This is what breaks when modules move: the code still imports, but every
    documented command and every cluster job silently points at nothing.
    """
    import re
    files = (["README.md", "patbinn.def", "data/README.md", "results/README.md",
              "scripts/README.md"]
             + glob.glob(os.path.join(ROOT, "docs", "*.md"))
             + glob.glob(os.path.join(ROOT, "scripts", "slurm", "*.sh")))
    pat = re.compile(r"python3 (?:/workspace/)?([A-Za-z0-9_./-]+\.py)")
    bad = []
    for f in files:
        path = f if os.path.isabs(f) else os.path.join(ROOT, f)
        if not os.path.exists(path):
            continue
        for i, line in enumerate(open(path, encoding="utf-8", errors="ignore"), 1):
            for m in pat.finditer(line):
                if not os.path.exists(os.path.join(ROOT, m.group(1))):
                    bad.append(f"{os.path.relpath(path, ROOT)}:{i} -> {m.group(1)}")
    assert not bad, "documented commands point at missing files:\n  " + "\n  ".join(bad)


def test_no_dangling_references_to_removed_files():
    """No published file points at code that is no longer in the repository.

    Only source files count as dangling: results/*.csv that a sweep script
    writes are outputs, and are regenerated rather than shipped.
    """
    files = _tracked_text_files()
    if files is None:
        return  # not a git checkout; nothing to verify
    removed = ["train_fasta.py", "evaluate_fasta.py", "Dockerfile.slurm",
               "docker-compose.yml"]
    hits = []
    for rel in files:
        if os.path.basename(rel) == os.path.basename(__file__):
            continue
        try:
            text = open(os.path.join(ROOT, rel), encoding="utf-8", errors="ignore").read()
        except OSError:
            continue
        for name in removed:
            if name in text:
                hits.append(f"{rel} -> {name}")
    assert not hits, "references to removed files:\n  " + "\n  ".join(hits)


def _main():
    tests = [(n, f) for n, f in sorted(globals().items())
             if n.startswith("test_") and callable(f)]
    failed = 0
    for name, fn in tests:
        try:
            fn()
            print(f"  PASS  {name}")
        except AssertionError as e:
            failed += 1
            print(f"  FAIL  {name}\n        {e}")
        except Exception as e:  # noqa: BLE001
            failed += 1
            print(f"  ERROR {name}: {type(e).__name__}: {e}")
    print(f"\n{len(tests) - failed}/{len(tests)} passed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(_main())
